@server = https://effective-space-palm-tree-qwggxwwg45g24gr4-8080.app.github.dev/
@mascotas = {{server}}/api/mascotas
@usuarios = {{server}}/api/usuarios
###
GET {{mascotas}}
###
POST {{mascotas}}
Content-Type: application/json

{
    "nombre": "Lazi",
    "edad": "1 año",
    "raza": "mestizo"
}
###
POST {{usuarios}}
Content-Type: application/json

{"nombre": "Otro Usuario"}
###
GET {{server}}/api/pacientes/1/mascota
###
GET {{server}}/api/especialistas/1/formacion